// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
/* This file was auto-generated by typesafe-i18n. Do not edit directly. */

import { initFormatters } from './formatters.js'
import type { Locales, Translations } from './i18n-types.js'
import { loadedFormatters, loadedLocales, locales } from './i18n-util.js'

import de from './de/index.js'
import en_US from './en-US/index.js'
import es from './es/index.js'
import fr from './fr/index.js'
import pt_BR from './pt-BR/index.js'

const localeTranslations = {
	de,
	'en-US': en_US,
	es,
	fr,
	'pt-BR': pt_BR,
}

export const loadLocale = (locale: Locales): void => {
	if (loadedLocales[locale]) return

	loadedLocales[locale] = localeTranslations[locale] as unknown as Translations
	loadFormatters(locale)
}

export const loadAllLocales = (): void => locales.forEach(loadLocale)

export const loadFormatters = (locale: Locales): void =>
	void (loadedFormatters[locale] = initFormatters(locale))
