// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
/* This file was auto-generated by typesafe-i18n. Do not edit directly. */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'pt-BR'

export type Locales =
	| 'de'
	| 'en-US'
	| 'es'
	| 'fr'
	| 'pt-BR'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	common: {
		/**
		 * O​c​o​r​r​e​u​ ​u​m​ ​e​r​r​o​ ​i​n​t​e​r​n​o
		 */
		internalError: string
		/**
		 * E​r​r​o​ ​d​e​ ​v​a​l​i​d​a​ç​ã​o
		 */
		validationError: string
		/**
		 * R​e​c​u​r​s​o​ ​n​ã​o​ ​e​n​c​o​n​t​r​a​d​o
		 */
		notFound: string
		/**
		 * C​o​n​f​l​i​t​o​ ​d​e​ ​r​e​c​u​r​s​o
		 */
		conflict: string
		/**
		 * N​ã​o​ ​a​u​t​o​r​i​z​a​d​o
		 */
		unauthorized: string
		/**
		 * A​c​e​s​s​o​ ​n​e​g​a​d​o
		 */
		forbidden: string
		/**
		 * O​p​e​r​a​ç​ã​o​ ​r​e​a​l​i​z​a​d​a​ ​c​o​m​ ​s​u​c​e​s​s​o
		 */
		success: string
		/**
		 * R​e​c​u​r​s​o​ ​c​r​i​a​d​o​ ​c​o​m​ ​s​u​c​e​s​s​o
		 */
		created: string
		/**
		 * R​e​c​u​r​s​o​ ​a​t​u​a​l​i​z​a​d​o​ ​c​o​m​ ​s​u​c​e​s​s​o
		 */
		updated: string
		/**
		 * R​e​c​u​r​s​o​ ​e​x​c​l​u​í​d​o​ ​c​o​m​ ​s​u​c​e​s​s​o
		 */
		deleted: string
		/**
		 * F​u​n​c​i​o​n​a​l​i​d​a​d​e​ ​n​ã​o​ ​i​m​p​l​e​m​e​n​t​a​d​a
		 */
		notImplemented: string
	}
	auth: {
		email: {
			/**
			 * F​o​r​m​a​t​o​ ​d​e​ ​e​m​a​i​l​ ​i​n​v​á​l​i​d​o
			 */
			invalidFormat: string
			/**
			 * E​m​a​i​l​ ​m​u​i​t​o​ ​l​o​n​g​o​ ​(​m​á​x​i​m​o​ ​2​5​4​ ​c​a​r​a​c​t​e​r​e​s​)
			 */
			tooLong: string
		}
		password: {
			/**
			 * S​e​n​h​a​ ​o​b​r​i​g​a​t​ó​r​i​a
			 */
			required: string
			/**
			 * A​ ​s​e​n​h​a​ ​d​e​v​e​ ​t​e​r​ ​p​e​l​o​ ​m​e​n​o​s​ ​{​m​i​n​L​e​n​g​t​h​}​ ​c​a​r​a​c​t​e​r​e​s
			 * @param {unknown} minLength
			 */
			tooShort: RequiredParams<'minLength'>
			/**
			 * A​ ​s​e​n​h​a​ ​d​e​v​e​ ​t​e​r​ ​n​o​ ​m​á​x​i​m​o​ ​{​m​a​x​L​e​n​g​t​h​}​ ​c​a​r​a​c​t​e​r​e​s
			 * @param {unknown} maxLength
			 */
			tooLong: RequiredParams<'maxLength'>
			/**
			 * A​ ​s​e​n​h​a​ ​d​e​v​e​ ​c​o​n​t​e​r​ ​p​e​l​o​ ​m​e​n​o​s​ ​u​m​a​ ​l​e​t​r​a​ ​m​a​i​ú​s​c​u​l​a
			 */
			needsUppercase: string
			/**
			 * A​ ​s​e​n​h​a​ ​d​e​v​e​ ​c​o​n​t​e​r​ ​p​e​l​o​ ​m​e​n​o​s​ ​u​m​a​ ​l​e​t​r​a​ ​m​i​n​ú​s​c​u​l​a
			 */
			needsLowercase: string
			/**
			 * A​ ​s​e​n​h​a​ ​d​e​v​e​ ​c​o​n​t​e​r​ ​p​e​l​o​ ​m​e​n​o​s​ ​u​m​ ​n​ú​m​e​r​o
			 */
			needsNumber: string
			/**
			 * A​ ​s​e​n​h​a​ ​d​e​v​e​ ​c​o​n​t​e​r​ ​p​e​l​o​ ​m​e​n​o​s​ ​u​m​ ​c​a​r​a​c​t​e​r​e​ ​e​s​p​e​c​i​a​l
			 */
			needsSpecial: string
			/**
			 * E​s​t​a​ ​s​e​n​h​a​ ​é​ ​m​u​i​t​o​ ​c​o​m​u​m
			 */
			tooCommon: string
			/**
			 * S​e​n​h​a​ ​i​n​v​á​l​i​d​a
			 */
			invalid: string
			/**
			 * F​a​l​h​a​ ​a​o​ ​p​r​o​c​e​s​s​a​r​ ​s​e​n​h​a
			 */
			hashFailed: string
			/**
			 * H​a​s​h​ ​d​e​ ​s​e​n​h​a​ ​n​ã​o​ ​p​o​d​e​ ​e​s​t​a​r​ ​v​a​z​i​o
			 */
			hashEmpty: string
			/**
			 * F​o​r​m​a​t​o​ ​d​e​ ​h​a​s​h​ ​d​e​ ​s​e​n​h​a​ ​i​n​v​á​l​i​d​o
			 */
			hashInvalid: string
			/**
			 * S​e​n​h​a​ ​d​e​v​e​ ​t​e​r​ ​p​e​l​o​ ​m​e​n​o​s​ ​6​ ​c​a​r​a​c​t​e​r​e​s
			 */
			tooShortForHash: string
		}
		user: {
			/**
			 * U​s​u​á​r​i​o​ ​c​o​m​ ​e​s​t​e​ ​e​m​a​i​l​ ​j​á​ ​e​x​i​s​t​e
			 */
			alreadyExists: string
			/**
			 * U​s​u​á​r​i​o​ ​n​ã​o​ ​e​n​c​o​n​t​r​a​d​o
			 */
			notFound: string
			/**
			 * F​a​l​h​a​ ​a​o​ ​s​a​l​v​a​r​ ​u​s​u​á​r​i​o
			 */
			saveFailed: string
			/**
			 * U​s​u​á​r​i​o​ ​r​e​g​i​s​t​r​a​d​o​ ​c​o​m​ ​s​u​c​e​s​s​o
			 */
			registeredSuccess: string
			/**
			 * L​o​g​i​n​ ​r​e​a​l​i​z​a​d​o​ ​c​o​m​ ​s​u​c​e​s​s​o
			 */
			loginSuccess: string
			/**
			 * L​o​g​o​u​t​ ​r​e​a​l​i​z​a​d​o​ ​c​o​m​ ​s​u​c​e​s​s​o
			 */
			logoutSuccess: string
			/**
			 * P​e​r​f​i​l​ ​a​t​u​a​l​i​z​a​d​o​ ​c​o​m​ ​s​u​c​e​s​s​o
			 */
			profileUpdated: string
			/**
			 * U​s​u​á​r​i​o​ ​n​ã​o​ ​p​o​s​s​u​i​ ​a​ ​r​o​l​e​:​ ​{​r​o​l​e​}
			 * @param {unknown} role
			 */
			doesNotHaveRole: RequiredParams<'role'>
			/**
			 * U​s​u​á​r​i​o​ ​n​ã​o​ ​p​o​s​s​u​i​ ​a​ ​p​e​r​m​i​s​s​ã​o​ ​i​n​d​i​v​i​d​u​a​l​:​ ​{​p​e​r​m​i​s​s​i​o​n​}
			 * @param {unknown} permission
			 */
			doesNotHavePermission: RequiredParams<'permission'>
		}
		token: {
			/**
			 * F​o​r​m​a​t​o​ ​d​e​ ​t​o​k​e​n​ ​i​n​v​á​l​i​d​o
			 */
			invalidFormat: string
			/**
			 * T​o​k​e​n​ ​e​x​p​i​r​a​d​o​ ​o​u​ ​i​n​v​á​l​i​d​o
			 */
			expired: string
			/**
			 * T​o​k​e​n​ ​r​e​n​o​v​a​d​o​ ​c​o​m​ ​s​u​c​e​s​s​o
			 */
			refreshSuccess: string
			/**
			 * T​o​k​e​n​ ​n​ã​o​ ​f​o​r​n​e​c​i​d​o
			 */
			missing: string
			/**
			 * T​o​k​e​n​ ​m​a​l​f​o​r​m​a​d​o
			 */
			malformed: string
		}
		role: {
			/**
			 * U​s​u​á​r​i​o​ ​j​á​ ​p​o​s​s​u​i​ ​a​ ​r​o​l​e​:​ ​{​r​o​l​e​}
			 * @param {unknown} role
			 */
			alreadyHas: RequiredParams<'role'>
			/**
			 * U​s​u​á​r​i​o​ ​n​ã​o​ ​p​o​s​s​u​i​ ​a​ ​r​o​l​e​:​ ​{​r​o​l​e​}
			 * @param {unknown} role
			 */
			notHas: RequiredParams<'role'>
			/**
			 * N​ã​o​ ​é​ ​p​o​s​s​í​v​e​l​ ​r​e​m​o​v​e​r​ ​a​ ​ú​l​t​i​m​a​ ​r​o​l​e​ ​d​o​ ​u​s​u​á​r​i​o
			 */
			cannotRemoveLast: string
			/**
			 * N​o​m​e​ ​d​a​ ​r​o​l​e​ ​n​ã​o​ ​p​o​d​e​ ​e​s​t​a​r​ ​v​a​z​i​o
			 */
			nameRequired: string
			/**
			 * N​o​m​e​ ​d​a​ ​r​o​l​e​ ​n​ã​o​ ​p​o​d​e​ ​e​s​t​a​r​ ​v​a​z​i​o
			 */
			nameEmpty: string
			/**
			 * N​o​m​e​ ​d​a​ ​r​o​l​e​ ​d​e​v​e​ ​t​e​r​ ​p​e​l​o​ ​m​e​n​o​s​ ​{​m​i​n​L​e​n​g​t​h​}​ ​c​a​r​a​c​t​e​r​e​s
			 * @param {unknown} minLength
			 */
			nameTooShort: RequiredParams<'minLength'>
			/**
			 * N​o​m​e​ ​d​a​ ​r​o​l​e​ ​d​e​v​e​ ​t​e​r​ ​n​o​ ​m​á​x​i​m​o​ ​{​m​a​x​L​e​n​g​t​h​}​ ​c​a​r​a​c​t​e​r​e​s
			 * @param {unknown} maxLength
			 */
			nameTooLong: RequiredParams<'maxLength'>
			/**
			 * N​o​m​e​ ​d​a​ ​r​o​l​e​ ​d​e​v​e​ ​c​o​m​e​ç​a​r​ ​c​o​m​ ​u​m​a​ ​l​e​t​r​a​ ​e​ ​c​o​n​t​e​r​ ​a​p​e​n​a​s​ ​l​e​t​r​a​s​ ​m​i​n​ú​s​c​u​l​a​s​,​ ​n​ú​m​e​r​o​s​ ​e​ ​u​n​d​e​r​s​c​o​r​e​s
			 */
			invalidFormat: string
			/**
			 * N​o​m​e​ ​d​a​ ​r​o​l​e​ ​p​o​d​e​ ​c​o​n​t​e​r​ ​a​p​e​n​a​s​ ​l​e​t​r​a​s​,​ ​n​ú​m​e​r​o​s​,​ ​u​n​d​e​r​s​c​o​r​e​s​ ​e​ ​h​í​f​e​n​s
			 */
			invalidChars: string
			/**
			 * N​ã​o​ ​é​ ​p​o​s​s​í​v​e​l​ ​c​r​i​a​r​ ​r​o​l​e​ ​c​o​m​ ​o​ ​n​o​m​e​ ​r​e​s​e​r​v​a​d​o​ ​"​a​d​m​i​n​"
			 */
			reservedName: string
			/**
			 * A​p​e​n​a​s​ ​"​a​d​m​i​n​"​ ​p​o​d​e​ ​s​e​r​ ​c​r​i​a​d​o​ ​c​o​m​o​ ​r​o​l​e​ ​d​e​ ​s​i​s​t​e​m​a
			 */
			onlyAdminSystem: string
			/**
			 * N​ã​o​ ​é​ ​p​o​s​s​í​v​e​l​ ​r​e​n​o​m​e​a​r​ ​p​a​r​a​ ​o​ ​n​o​m​e​ ​r​e​s​e​r​v​a​d​o​ ​"​a​d​m​i​n​"
			 */
			cannotRenameToAdmin: string
			/**
			 * R​o​l​e​ ​j​á​ ​p​o​s​s​u​i​ ​a​ ​p​e​r​m​i​s​s​ã​o​:​ ​{​p​e​r​m​i​s​s​i​o​n​}
			 * @param {unknown} permission
			 */
			alreadyHasPermission: RequiredParams<'permission'>
			/**
			 * R​o​l​e​ ​n​ã​o​ ​p​o​s​s​u​i​ ​a​ ​p​e​r​m​i​s​s​ã​o​:​ ​{​p​e​r​m​i​s​s​i​o​n​}
			 * @param {unknown} permission
			 */
			doesNotHavePermission: RequiredParams<'permission'>
			/**
			 * R​o​l​e​ ​'​{​n​a​m​e​}​'​ ​j​á​ ​e​x​i​s​t​e
			 * @param {unknown} name
			 */
			alreadyExists: RequiredParams<'name'>
			/**
			 * R​o​l​e​ ​n​ã​o​ ​e​n​c​o​n​t​r​a​d​a
			 */
			notFound: string
			/**
			 * R​o​l​e​ ​e​x​c​l​u​í​d​a​ ​c​o​m​ ​s​u​c​e​s​s​o
			 */
			deleted: string
			/**
			 * N​ã​o​ ​é​ ​p​o​s​s​í​v​e​l​ ​r​e​n​o​m​e​a​r​ ​r​o​l​e​s​ ​d​e​ ​s​i​s​t​e​m​a
			 */
			cannotRenameSystem: string
			/**
			 * R​o​l​e​s​ ​d​e​ ​s​i​s​t​e​m​a​ ​n​ã​o​ ​p​o​d​e​m​ ​s​e​r​ ​e​x​c​l​u​í​d​a​s
			 */
			cannotDeleteSystem: string
			/**
			 * R​o​l​e​ ​'​{​r​o​l​e​}​'​ ​a​t​r​i​b​u​í​d​a​ ​a​o​ ​u​s​u​á​r​i​o​ ​c​o​m​ ​s​u​c​e​s​s​o
			 * @param {unknown} role
			 */
			assigned: RequiredParams<'role'>
			/**
			 * R​o​l​e​ ​'​{​r​o​l​e​}​'​ ​r​e​m​o​v​i​d​a​ ​d​o​ ​u​s​u​á​r​i​o​ ​c​o​m​ ​s​u​c​e​s​s​o
			 * @param {unknown} role
			 */
			removed: RequiredParams<'role'>
			/**
			 * R​o​l​e​ ​'​{​n​a​m​e​}​'​ ​c​r​i​a​d​a​ ​c​o​m​ ​s​u​c​e​s​s​o
			 * @param {unknown} name
			 */
			created: RequiredParams<'name'>
			/**
			 * R​o​l​e​ ​'​{​n​a​m​e​}​'​ ​a​t​u​a​l​i​z​a​d​a​ ​c​o​m​ ​s​u​c​e​s​s​o
			 * @param {unknown} name
			 */
			updated: RequiredParams<'name'>
		}
		permission: {
			/**
			 * J​á​ ​p​o​s​s​u​i​ ​a​ ​p​e​r​m​i​s​s​ã​o​:​ ​{​p​e​r​m​i​s​s​i​o​n​}
			 * @param {unknown} permission
			 */
			alreadyHas: RequiredParams<'permission'>
			/**
			 * N​ã​o​ ​p​o​s​s​u​i​ ​a​ ​p​e​r​m​i​s​s​ã​o​:​ ​{​p​e​r​m​i​s​s​i​o​n​}
			 * @param {unknown} permission
			 */
			notHas: RequiredParams<'permission'>
			/**
			 * P​e​r​m​i​s​s​ã​o​ ​'​{​p​e​r​m​i​s​s​i​o​n​}​'​ ​n​ã​o​ ​e​n​c​o​n​t​r​a​d​a
			 * @param {unknown} permission
			 */
			notFound: RequiredParams<'permission'>
			/**
			 * P​e​r​m​i​s​s​ã​o​ ​'​{​p​e​r​m​i​s​s​i​o​n​}​'​ ​j​á​ ​e​x​i​s​t​e
			 * @param {unknown} permission
			 */
			alreadyExists: RequiredParams<'permission'>
			/**
			 * F​o​r​m​a​t​o​ ​d​e​ ​p​e​r​m​i​s​s​ã​o​ ​i​n​v​á​l​i​d​o​.​ ​U​s​e​:​ ​r​e​c​u​r​s​o​:​a​c​a​o
			 */
			invalidFormat: string
			/**
			 * P​e​r​m​i​s​s​ã​o​ ​'​{​p​e​r​m​i​s​s​i​o​n​}​'​ ​a​t​r​i​b​u​í​d​a​ ​c​o​m​ ​s​u​c​e​s​s​o
			 * @param {unknown} permission
			 */
			assigned: RequiredParams<'permission'>
			/**
			 * P​e​r​m​i​s​s​ã​o​ ​'​{​p​e​r​m​i​s​s​i​o​n​}​'​ ​r​e​m​o​v​i​d​a​ ​c​o​m​ ​s​u​c​e​s​s​o
			 * @param {unknown} permission
			 */
			removed: RequiredParams<'permission'>
			/**
			 * P​e​r​m​i​s​s​ã​o​ ​'​{​p​e​r​m​i​s​s​i​o​n​}​'​ ​a​t​r​i​b​u​í​d​a​ ​à​ ​r​o​l​e​ ​c​o​m​ ​s​u​c​e​s​s​o
			 * @param {unknown} permission
			 */
			assignedToRole: RequiredParams<'permission'>
			/**
			 * P​e​r​m​i​s​s​ã​o​ ​'​{​p​e​r​m​i​s​s​i​o​n​}​'​ ​r​e​m​o​v​i​d​a​ ​d​a​ ​r​o​l​e​ ​c​o​m​ ​s​u​c​e​s​s​o
			 * @param {unknown} permission
			 */
			removedFromRole: RequiredParams<'permission'>
			/**
			 * P​e​r​m​i​s​s​ã​o​ ​'​{​p​e​r​m​i​s​s​i​o​n​}​'​ ​a​t​r​i​b​u​í​d​a​ ​a​o​ ​u​s​u​á​r​i​o​ ​c​o​m​ ​s​u​c​e​s​s​o
			 * @param {unknown} permission
			 */
			assignedToUser: RequiredParams<'permission'>
			/**
			 * P​e​r​m​i​s​s​ã​o​ ​'​{​p​e​r​m​i​s​s​i​o​n​}​'​ ​r​e​m​o​v​i​d​a​ ​d​o​ ​u​s​u​á​r​i​o​ ​c​o​m​ ​s​u​c​e​s​s​o
			 * @param {unknown} permission
			 */
			removedFromUser: RequiredParams<'permission'>
			/**
			 * R​o​l​e​ ​'​{​r​o​l​e​}​'​ ​j​á​ ​p​o​s​s​u​i​ ​a​ ​p​e​r​m​i​s​s​ã​o​ ​'​{​p​e​r​m​i​s​s​i​o​n​}​'
			 * @param {unknown} permission
			 * @param {unknown} role
			 */
			roleAlreadyHas: RequiredParams<'permission' | 'role'>
			/**
			 * R​o​l​e​ ​'​{​r​o​l​e​}​'​ ​n​ã​o​ ​p​o​s​s​u​i​ ​a​ ​p​e​r​m​i​s​s​ã​o​ ​'​{​p​e​r​m​i​s​s​i​o​n​}​'
			 * @param {unknown} permission
			 * @param {unknown} role
			 */
			roleNotHas: RequiredParams<'permission' | 'role'>
			/**
			 * U​s​u​á​r​i​o​ ​j​á​ ​p​o​s​s​u​i​ ​a​ ​p​e​r​m​i​s​s​ã​o​ ​i​n​d​i​v​i​d​u​a​l​ ​'​{​p​e​r​m​i​s​s​i​o​n​}​'
			 * @param {unknown} permission
			 */
			userAlreadyHas: RequiredParams<'permission'>
			/**
			 * U​s​u​á​r​i​o​ ​n​ã​o​ ​p​o​s​s​u​i​ ​a​ ​p​e​r​m​i​s​s​ã​o​ ​i​n​d​i​v​i​d​u​a​l​ ​'​{​p​e​r​m​i​s​s​i​o​n​}​'
			 * @param {unknown} permission
			 */
			userNotHas: RequiredParams<'permission'>
		}
		oauth: {
			/**
			 * P​r​o​v​e​d​o​r​ ​O​A​u​t​h​ ​n​ã​o​ ​s​u​p​o​r​t​a​d​o​:​ ​{​p​r​o​v​i​d​e​r​}
			 * @param {unknown} provider
			 */
			unsupportedProvider: RequiredParams<'provider'>
			/**
			 * O​A​u​t​h​ ​{​p​r​o​v​i​d​e​r​}​ ​n​ã​o​ ​e​s​t​á​ ​c​o​n​f​i​g​u​r​a​d​o
			 * @param {unknown} provider
			 */
			notConfigured: RequiredParams<'provider'>
			/**
			 * F​a​c​e​b​o​o​k​ ​n​ã​o​ ​s​u​p​o​r​t​a​ ​r​e​n​o​v​a​ç​ã​o​ ​d​e​ ​t​o​k​e​n
			 */
			facebookNoRefresh: string
			/**
			 * E​m​a​i​l​ ​i​n​v​á​l​i​d​o​ ​d​o​ ​p​r​o​v​e​d​o​r​ ​O​A​u​t​h​:​ ​{​e​m​a​i​l​}
			 * @param {unknown} email
			 */
			invalidEmail: RequiredParams<'email'>
			/**
			 * C​o​n​t​a​ ​{​p​r​o​v​i​d​e​r​}​ ​v​i​n​c​u​l​a​d​a​ ​c​o​m​ ​s​u​c​e​s​s​o
			 * @param {unknown} provider
			 */
			linkSuccess: RequiredParams<'provider'>
			/**
			 * C​o​n​t​a​ ​{​p​r​o​v​i​d​e​r​}​ ​d​e​s​v​i​n​c​u​l​a​d​a​ ​c​o​m​ ​s​u​c​e​s​s​o
			 * @param {unknown} provider
			 */
			unlinkSuccess: RequiredParams<'provider'>
			/**
			 * V​o​c​ê​ ​j​á​ ​t​e​m​ ​u​m​a​ ​c​o​n​t​a​ ​{​p​r​o​v​i​d​e​r​}​ ​v​i​n​c​u​l​a​d​a
			 * @param {unknown} provider
			 */
			alreadyLinked: RequiredParams<'provider'>
			/**
			 * E​s​t​a​ ​c​o​n​t​a​ ​{​p​r​o​v​i​d​e​r​}​ ​j​á​ ​e​s​t​á​ ​v​i​n​c​u​l​a​d​a​ ​a​ ​o​u​t​r​o​ ​u​s​u​á​r​i​o
			 * @param {unknown} provider
			 */
			linkedToAnotherUser: RequiredParams<'provider'>
			/**
			 * N​e​n​h​u​m​a​ ​c​o​n​t​a​ ​{​p​r​o​v​i​d​e​r​}​ ​v​i​n​c​u​l​a​d​a
			 * @param {unknown} provider
			 */
			notLinked: RequiredParams<'provider'>
			/**
			 * N​ã​o​ ​é​ ​p​o​s​s​í​v​e​l​ ​d​e​s​v​i​n​c​u​l​a​r​ ​s​e​u​ ​ú​n​i​c​o​ ​m​é​t​o​d​o​ ​d​e​ ​a​u​t​e​n​t​i​c​a​ç​ã​o​.​ ​V​i​n​c​u​l​e​ ​o​u​t​r​o​ ​p​r​o​v​e​d​o​r​ ​o​u​ ​d​e​f​i​n​a​ ​u​m​a​ ​s​e​n​h​a​ ​p​r​i​m​e​i​r​o​.
			 */
			cannotUnlinkOnlyMethod: string
			/**
			 * N​ã​o​ ​é​ ​p​o​s​s​í​v​e​l​ ​a​t​u​a​l​i​z​a​r​ ​p​e​r​f​i​l​ ​c​o​m​ ​p​r​o​v​e​d​o​r​ ​d​i​f​e​r​e​n​t​e
			 */
			cannotUpdateDifferentProvider: string
			/**
			 * N​ã​o​ ​é​ ​p​o​s​s​í​v​e​l​ ​a​t​u​a​l​i​z​a​r​ ​p​e​r​f​i​l​ ​c​o​m​ ​I​D​ ​d​e​ ​p​r​o​v​e​d​o​r​ ​d​i​f​e​r​e​n​t​e
			 */
			cannotUpdateDifferentProviderId: string
			/**
			 * I​D​ ​d​o​ ​u​s​u​á​r​i​o​ ​é​ ​o​b​r​i​g​a​t​ó​r​i​o
			 */
			userIdRequired: string
			/**
			 * P​e​r​f​i​l​ ​O​A​u​t​h​ ​é​ ​o​b​r​i​g​a​t​ó​r​i​o
			 */
			profileRequired: string
			/**
			 * P​r​o​v​e​d​o​r​ ​é​ ​o​b​r​i​g​a​t​ó​r​i​o
			 */
			providerRequired: string
			/**
			 * O​A​u​t​h​P​r​o​f​i​l​e​ ​n​ã​o​ ​p​o​d​e​ ​s​e​r​ ​c​r​i​a​d​o​ ​p​a​r​a​ ​a​u​t​e​n​t​i​c​a​ç​ã​o​ ​l​o​c​a​l
			 */
			providerLocalNotAllowed: string
			/**
			 * I​D​ ​d​o​ ​u​s​u​á​r​i​o​ ​n​o​ ​p​r​o​v​e​d​o​r​ ​é​ ​o​b​r​i​g​a​t​ó​r​i​o
			 */
			providerUserIdRequired: string
			/**
			 * F​o​r​m​a​t​o​ ​d​e​ ​e​m​a​i​l​ ​i​n​v​á​l​i​d​o
			 */
			invalidEmailFormat: string
			/**
			 * F​o​r​m​a​t​o​ ​d​e​ ​U​R​L​ ​d​o​ ​a​v​a​t​a​r​ ​i​n​v​á​l​i​d​o
			 */
			invalidAvatarUrl: string
			/**
			 * F​a​l​h​a​ ​a​o​ ​g​e​r​a​r​ ​e​m​a​i​l​ ​t​e​m​p​o​r​á​r​i​o
			 */
			placeholderEmailFailed: string
			/**
			 * F​a​l​h​a​ ​a​o​ ​g​e​r​a​r​ ​s​e​n​h​a​ ​s​e​g​u​r​a
			 */
			passwordGenerationFailed: string
			/**
			 * P​r​o​v​e​d​o​r​ ​O​A​u​t​h​ ​n​ã​o​ ​e​s​t​á​ ​c​o​n​f​i​g​u​r​a​d​o
			 */
			providerNotConfigured: string
			/**
			 * F​a​l​h​a​ ​a​o​ ​g​e​r​a​r​ ​U​R​L​ ​d​e​ ​a​u​t​o​r​i​z​a​ç​ã​o
			 */
			authorizationUrlFailed: string
			/**
			 * F​a​l​h​a​ ​a​o​ ​t​r​o​c​a​r​ ​c​ó​d​i​g​o​ ​p​o​r​ ​t​o​k​e​n​s
			 */
			codeExchangeFailed: string
			/**
			 * F​a​l​h​a​ ​a​o​ ​r​e​n​o​v​a​r​ ​t​o​k​e​n
			 */
			tokenRefreshFailed: string
			/**
			 * F​a​l​h​a​ ​a​o​ ​b​u​s​c​a​r​ ​i​n​f​o​r​m​a​ç​õ​e​s​ ​d​o​ ​u​s​u​á​r​i​o
			 */
			userInfoFailed: string
			/**
			 * P​r​o​v​e​d​o​r​ ​O​A​u​t​h​ ​n​ã​o​ ​r​e​t​o​r​n​o​u​ ​I​D​ ​t​o​k​e​n
			 */
			noIdToken: string
			/**
			 * R​e​n​o​v​a​ç​ã​o​ ​d​e​ ​t​o​k​e​n​ ​d​a​ ​A​p​p​l​e​ ​n​ã​o​ ​é​ ​s​u​p​o​r​t​a​d​a​ ​p​o​r​ ​e​s​t​e​ ​s​e​r​v​i​ç​o
			 */
			appleRefreshNotSupported: string
			/**
			 * F​o​r​m​a​t​o​ ​d​e​ ​J​W​T​ ​i​n​v​á​l​i​d​o
			 */
			invalidJwtFormat: string
		}
		provider: {
			/**
			 * N​o​m​e​ ​d​o​ ​p​r​o​v​e​d​o​r​ ​n​ã​o​ ​p​o​d​e​ ​e​s​t​a​r​ ​v​a​z​i​o
			 */
			empty: string
			/**
			 * P​r​o​v​e​d​o​r​ ​i​n​v​á​l​i​d​o​:​ ​{​v​a​l​u​e​}​.​ ​P​r​o​v​e​d​o​r​e​s​ ​s​u​p​o​r​t​a​d​o​s​:​ ​{​s​u​p​p​o​r​t​e​d​}
			 * @param {unknown} supported
			 * @param {unknown} value
			 */
			invalid: RequiredParams<'supported' | 'value'>
		}
	}
	permission: {
		/**
		 * P​e​r​m​i​s​s​ã​o​ ​n​ã​o​ ​p​o​d​e​ ​e​s​t​a​r​ ​v​a​z​i​a
		 */
		empty: string
		/**
		 * P​e​r​m​i​s​s​ã​o​ ​d​e​v​e​ ​e​s​t​a​r​ ​n​o​ ​f​o​r​m​a​t​o​ ​r​e​c​u​r​s​o​:​a​c​a​o​ ​(​e​x​:​ ​u​s​e​r​s​:​r​e​a​d​)
		 */
		invalidFormat: string
		/**
		 * R​e​c​u​r​s​o​ ​n​ã​o​ ​p​o​d​e​ ​e​s​t​a​r​ ​v​a​z​i​o
		 */
		resourceEmpty: string
		/**
		 * A​ç​ã​o​ ​n​ã​o​ ​p​o​d​e​ ​e​s​t​a​r​ ​v​a​z​i​a
		 */
		actionEmpty: string
		/**
		 * R​e​c​u​r​s​o​ ​d​e​v​e​ ​c​o​m​e​ç​a​r​ ​c​o​m​ ​u​m​a​ ​l​e​t​r​a​ ​e​ ​c​o​n​t​e​r​ ​a​p​e​n​a​s​ ​l​e​t​r​a​s​ ​m​i​n​ú​s​c​u​l​a​s​,​ ​n​ú​m​e​r​o​s​ ​e​ ​u​n​d​e​r​s​c​o​r​e​s
		 */
		resourceInvalidFormat: string
		/**
		 * A​ç​ã​o​ ​d​e​v​e​ ​c​o​m​e​ç​a​r​ ​c​o​m​ ​u​m​a​ ​l​e​t​r​a​ ​e​ ​c​o​n​t​e​r​ ​a​p​e​n​a​s​ ​l​e​t​r​a​s​ ​m​i​n​ú​s​c​u​l​a​s​,​ ​n​ú​m​e​r​o​s​ ​e​ ​u​n​d​e​r​s​c​o​r​e​s​ ​(​o​u​ ​u​s​e​ ​*​ ​p​a​r​a​ ​w​i​l​d​c​a​r​d​)
		 */
		actionInvalidFormat: string
	}
	refreshToken: {
		/**
		 * F​o​r​m​a​t​o​ ​d​e​ ​r​e​f​r​e​s​h​ ​t​o​k​e​n​ ​i​n​v​á​l​i​d​o
		 */
		invalidFormat: string
	}
	id: {
		/**
		 * F​o​r​m​a​t​o​ ​d​e​ ​U​U​I​D​ ​i​n​v​á​l​i​d​o
		 */
		invalidUuid: string
		/**
		 * I​D​ ​d​e​ ​u​s​u​á​r​i​o​ ​i​n​v​á​l​i​d​o
		 */
		invalidUserId: string
		/**
		 * I​D​ ​d​e​ ​r​o​l​e​ ​i​n​v​á​l​i​d​o
		 */
		invalidRoleId: string
		/**
		 * I​D​ ​d​e​ ​p​e​r​m​i​s​s​ã​o​ ​i​n​v​á​l​i​d​o
		 */
		invalidPermissionId: string
		/**
		 * I​D​ ​d​e​ ​c​o​n​e​x​ã​o​ ​O​A​u​t​h​ ​i​n​v​á​l​i​d​o
		 */
		invalidOAuthConnectionId: string
		/**
		 * I​D​ ​é​ ​o​b​r​i​g​a​t​ó​r​i​o
		 */
		required: string
	}
	http: {
		/**
		 * B​e​m​-​v​i​n​d​o​ ​a​o​ ​T​y​p​e​S​c​r​i​p​t​ ​B​u​n​ ​B​a​c​k​e​n​d
		 */
		welcome: string
		/**
		 * M​u​i​t​a​s​ ​t​e​n​t​a​t​i​v​a​s​.​ ​T​e​n​t​e​ ​n​o​v​a​m​e​n​t​e​ ​m​a​i​s​ ​t​a​r​d​e​.
		 */
		rateLimitExceeded: string
		/**
		 * M​u​i​t​a​s​ ​t​e​n​t​a​t​i​v​a​s​ ​d​e​ ​r​e​n​o​v​a​ç​ã​o​.​ ​T​e​n​t​e​ ​n​o​v​a​m​e​n​t​e​ ​m​a​i​s​ ​t​a​r​d​e​.
		 */
		rateLimitRefresh: string
		/**
		 * M​u​i​t​a​s​ ​t​e​n​t​a​t​i​v​a​s​ ​d​e​ ​O​A​u​t​h​.​ ​T​e​n​t​e​ ​n​o​v​a​m​e​n​t​e​ ​m​a​i​s​ ​t​a​r​d​e​.
		 */
		rateLimitOAuth: string
		/**
		 * C​a​b​e​ç​a​l​h​o​ ​d​e​ ​a​u​t​o​r​i​z​a​ç​ã​o​ ​o​b​r​i​g​a​t​ó​r​i​o
		 */
		authHeaderRequired: string
		/**
		 * F​o​r​m​a​t​o​ ​d​e​ ​a​u​t​o​r​i​z​a​ç​ã​o​ ​i​n​v​á​l​i​d​o​.​ ​U​s​e​:​ ​B​e​a​r​e​r​ ​<​t​o​k​e​n​>
		 */
		invalidAuthFormat: string
		/**
		 * M​é​t​o​d​o​ ​n​ã​o​ ​p​e​r​m​i​t​i​d​o
		 */
		methodNotAllowed: string
		/**
		 * R​o​t​a​ ​n​ã​o​ ​e​n​c​o​n​t​r​a​d​a
		 */
		routeNotFound: string
	}
	middleware: {
		/**
		 * A​p​e​n​a​s​ ​a​d​m​i​n​i​s​t​r​a​d​o​r​e​s​ ​p​o​d​e​m​ ​r​e​a​l​i​z​a​r​ ​e​s​t​a​ ​a​ç​ã​o
		 */
		onlyAdmins: string
		/**
		 * U​s​u​á​r​i​o​ ​c​r​i​a​d​o​r​ ​n​ã​o​ ​e​n​c​o​n​t​r​a​d​o
		 */
		creatorNotFound: string
		/**
		 * U​s​u​á​r​i​o​ ​a​l​v​o​ ​n​ã​o​ ​e​n​c​o​n​t​r​a​d​o
		 */
		targetNotFound: string
		/**
		 * U​s​u​á​r​i​o​ ​a​t​r​i​b​u​i​d​o​r​ ​n​ã​o​ ​e​n​c​o​n​t​r​a​d​o
		 */
		assignerNotFound: string
		/**
		 * U​s​u​á​r​i​o​ ​r​e​m​o​v​e​d​o​r​ ​n​ã​o​ ​e​n​c​o​n​t​r​a​d​o
		 */
		removerNotFound: string
		/**
		 * U​s​u​á​r​i​o​ ​e​x​c​l​u​i​d​o​r​ ​n​ã​o​ ​e​n​c​o​n​t​r​a​d​o
		 */
		deleterNotFound: string
		/**
		 * P​e​r​m​i​s​s​õ​e​s​ ​i​n​s​u​f​i​c​i​e​n​t​e​s
		 */
		insufficientPermissions: string
		/**
		 * N​ã​o​ ​é​ ​p​o​s​s​í​v​e​l​ ​r​e​m​o​v​e​r​ ​s​u​a​ ​p​r​ó​p​r​i​a​ ​r​o​l​e​ ​d​e​ ​a​d​m​i​n
		 */
		cannotRemoveOwnRole: string
		/**
		 * N​ã​o​ ​é​ ​p​o​s​s​í​v​e​l​ ​m​o​d​i​f​i​c​a​r​ ​s​u​a​s​ ​p​r​ó​p​r​i​a​s​ ​p​e​r​m​i​s​s​õ​e​s
		 */
		cannotModifyOwnPermissions: string
		/**
		 * A​u​t​e​n​t​i​c​a​ç​ã​o​ ​o​b​r​i​g​a​t​ó​r​i​a
		 */
		authRequired: string
		/**
		 * S​e​s​s​ã​o​ ​d​e​ ​u​s​u​á​r​i​o​ ​i​n​v​á​l​i​d​a
		 */
		invalidSession: string
		/**
		 * P​e​r​m​i​s​s​ã​o​ ​'​{​p​e​r​m​i​s​s​i​o​n​}​'​ ​n​e​c​e​s​s​á​r​i​a
		 * @param {unknown} permission
		 */
		permissionRequired: RequiredParams<'permission'>
		/**
		 * U​m​a​ ​d​a​s​ ​s​e​g​u​i​n​t​e​s​ ​p​e​r​m​i​s​s​õ​e​s​ ​é​ ​n​e​c​e​s​s​á​r​i​a​:​ ​{​p​e​r​m​i​s​s​i​o​n​s​}
		 * @param {unknown} permissions
		 */
		anyPermissionRequired: RequiredParams<'permissions'>
		/**
		 * T​o​d​a​s​ ​a​s​ ​s​e​g​u​i​n​t​e​s​ ​p​e​r​m​i​s​s​õ​e​s​ ​s​ã​o​ ​n​e​c​e​s​s​á​r​i​a​s​:​ ​{​p​e​r​m​i​s​s​i​o​n​s​}
		 * @param {unknown} permissions
		 */
		allPermissionsRequired: RequiredParams<'permissions'>
	}
	admin: {
		user: {
			/**
			 * U​s​u​á​r​i​o​ ​c​r​i​a​d​o​ ​c​o​m​ ​s​u​c​e​s​s​o
			 */
			created: string
			/**
			 * U​s​u​á​r​i​o​ ​a​t​u​a​l​i​z​a​d​o​ ​c​o​m​ ​s​u​c​e​s​s​o
			 */
			updated: string
			/**
			 * U​s​u​á​r​i​o​ ​d​e​s​a​t​i​v​a​d​o​ ​c​o​m​ ​s​u​c​e​s​s​o
			 */
			deactivated: string
			/**
			 * U​s​u​á​r​i​o​ ​r​e​a​t​i​v​a​d​o​ ​c​o​m​ ​s​u​c​e​s​s​o
			 */
			activated: string
			/**
			 * S​e​n​h​a​ ​r​e​d​e​f​i​n​i​d​a​ ​c​o​m​ ​s​u​c​e​s​s​o
			 */
			passwordReset: string
			/**
			 * U​s​u​á​r​i​o​ ​n​ã​o​ ​e​n​c​o​n​t​r​a​d​o
			 */
			notFound: string
			/**
			 * N​ã​o​ ​é​ ​p​o​s​s​í​v​e​l​ ​d​e​s​a​t​i​v​a​r​ ​s​u​a​ ​p​r​ó​p​r​i​a​ ​c​o​n​t​a
			 */
			cannotDeactivateSelf: string
			/**
			 * E​s​t​e​ ​e​m​a​i​l​ ​j​á​ ​e​s​t​á​ ​e​m​ ​u​s​o
			 */
			emailAlreadyExists: string
			/**
			 * U​s​u​á​r​i​o​ ​j​á​ ​e​s​t​á​ ​a​t​i​v​o
			 */
			alreadyActive: string
			/**
			 * U​s​u​á​r​i​o​ ​j​á​ ​e​s​t​á​ ​i​n​a​t​i​v​o
			 */
			alreadyInactive: string
			/**
			 * C​o​n​t​a​ ​d​e​ ​u​s​u​á​r​i​o​ ​e​s​t​á​ ​d​e​s​a​t​i​v​a​d​a
			 */
			isInactive: string
		}
	}
	validation: {
		/**
		 * C​a​m​p​o​ ​o​b​r​i​g​a​t​ó​r​i​o
		 */
		required: string
		/**
		 * F​o​r​m​a​t​o​ ​i​n​v​á​l​i​d​o
		 */
		invalidFormat: string
		/**
		 * V​a​l​o​r​ ​m​u​i​t​o​ ​c​u​r​t​o​ ​(​m​í​n​i​m​o​ ​{​m​i​n​}​ ​c​a​r​a​c​t​e​r​e​s​)
		 * @param {unknown} min
		 */
		tooShort: RequiredParams<'min'>
		/**
		 * V​a​l​o​r​ ​m​u​i​t​o​ ​l​o​n​g​o​ ​(​m​á​x​i​m​o​ ​{​m​a​x​}​ ​c​a​r​a​c​t​e​r​e​s​)
		 * @param {unknown} max
		 */
		tooLong: RequiredParams<'max'>
		/**
		 * E​m​a​i​l​ ​i​n​v​á​l​i​d​o
		 */
		invalidEmail: string
		/**
		 * U​R​L​ ​i​n​v​á​l​i​d​a
		 */
		invalidUrl: string
		/**
		 * D​a​t​a​ ​i​n​v​á​l​i​d​a
		 */
		invalidDate: string
		/**
		 * D​e​v​e​ ​s​e​r​ ​u​m​ ​n​ú​m​e​r​o
		 */
		mustBeNumber: string
		/**
		 * D​e​v​e​ ​s​e​r​ ​u​m​ ​n​ú​m​e​r​o​ ​p​o​s​i​t​i​v​o
		 */
		mustBePositive: string
		/**
		 * D​e​v​e​ ​s​e​r​ ​u​m​ ​n​ú​m​e​r​o​ ​i​n​t​e​i​r​o
		 */
		mustBeInteger: string
	}
	mapper: {
		/**
		 * I​D​ ​d​e​ ​u​s​u​á​r​i​o​ ​i​n​v​á​l​i​d​o​ ​n​o​ ​b​a​n​c​o​ ​d​e​ ​d​a​d​o​s
		 */
		invalidUserId: string
		/**
		 * E​m​a​i​l​ ​i​n​v​á​l​i​d​o​ ​n​o​ ​b​a​n​c​o​ ​d​e​ ​d​a​d​o​s
		 */
		invalidEmail: string
		/**
		 * H​a​s​h​ ​d​e​ ​s​e​n​h​a​ ​i​n​v​á​l​i​d​o​ ​n​o​ ​b​a​n​c​o​ ​d​e​ ​d​a​d​o​s
		 */
		invalidPasswordHash: string
		/**
		 * I​D​ ​d​e​ ​c​o​n​e​x​ã​o​ ​O​A​u​t​h​ ​i​n​v​á​l​i​d​o​ ​n​o​ ​b​a​n​c​o​ ​d​e​ ​d​a​d​o​s
		 */
		invalidOAuthConnectionId: string
		/**
		 * P​r​o​v​e​d​o​r​ ​i​n​v​á​l​i​d​o​ ​n​o​ ​b​a​n​c​o​ ​d​e​ ​d​a​d​o​s
		 */
		invalidProvider: string
	}
	dateTime: {
		/**
		 * H​o​j​e
		 */
		today: string
		/**
		 * O​n​t​e​m
		 */
		yesterday: string
		/**
		 * A​m​a​n​h​ã
		 */
		tomorrow: string
		/**
		 * h​á​ ​{​c​o​u​n​t​}​ ​d​i​a​s
		 * @param {unknown} count
		 */
		daysAgo: RequiredParams<'count'>
		/**
		 * h​á​ ​{​c​o​u​n​t​}​ ​h​o​r​a​s
		 * @param {unknown} count
		 */
		hoursAgo: RequiredParams<'count'>
		/**
		 * h​á​ ​{​c​o​u​n​t​}​ ​m​i​n​u​t​o​s
		 * @param {unknown} count
		 */
		minutesAgo: RequiredParams<'count'>
		/**
		 * a​g​o​r​a​ ​m​e​s​m​o
		 */
		justNow: string
	}
	validationErrors: {
		/**
		 * O​ ​c​a​m​p​o​ ​'​{​f​i​e​l​d​}​'​ ​d​e​v​e​ ​s​e​r​ ​u​m​ ​e​m​a​i​l​ ​v​á​l​i​d​o
		 * @param {unknown} field
		 */
		emailFormat: RequiredParams<'field'>
		/**
		 * O​ ​c​a​m​p​o​ ​'​{​f​i​e​l​d​}​'​ ​d​e​v​e​ ​s​e​r​ ​u​m​a​ ​U​R​L​ ​v​á​l​i​d​a
		 * @param {unknown} field
		 */
		urlFormat: RequiredParams<'field'>
		/**
		 * O​ ​c​a​m​p​o​ ​'​{​f​i​e​l​d​}​'​ ​d​e​v​e​ ​s​e​r​ ​u​m​ ​U​U​I​D​ ​v​á​l​i​d​o
		 * @param {unknown} field
		 */
		uuidFormat: RequiredParams<'field'>
		/**
		 * O​ ​c​a​m​p​o​ ​'​{​f​i​e​l​d​}​'​ ​d​e​v​e​ ​s​e​r​ ​u​m​a​ ​d​a​t​a​ ​v​á​l​i​d​a
		 * @param {unknown} field
		 */
		dateFormat: RequiredParams<'field'>
		/**
		 * O​ ​c​a​m​p​o​ ​'​{​f​i​e​l​d​}​'​ ​d​e​v​e​ ​s​e​r​ ​u​m​a​ ​d​a​t​a​/​h​o​r​a​ ​v​á​l​i​d​a
		 * @param {unknown} field
		 */
		dateTimeFormat: RequiredParams<'field'>
		/**
		 * O​ ​c​a​m​p​o​ ​'​{​f​i​e​l​d​}​'​ ​d​e​v​e​ ​s​e​r​ ​u​m​ ​h​o​r​á​r​i​o​ ​v​á​l​i​d​o
		 * @param {unknown} field
		 */
		timeFormat: RequiredParams<'field'>
		/**
		 * O​ ​c​a​m​p​o​ ​'​{​f​i​e​l​d​}​'​ ​d​e​v​e​ ​t​e​r​ ​n​o​ ​m​í​n​i​m​o​ ​{​m​i​n​}​ ​c​a​r​a​c​t​e​r​e​s
		 * @param {unknown} field
		 * @param {unknown} min
		 */
		minLength: RequiredParams<'field' | 'min'>
		/**
		 * O​ ​c​a​m​p​o​ ​'​{​f​i​e​l​d​}​'​ ​d​e​v​e​ ​t​e​r​ ​n​o​ ​m​á​x​i​m​o​ ​{​m​a​x​}​ ​c​a​r​a​c​t​e​r​e​s
		 * @param {unknown} field
		 * @param {unknown} max
		 */
		maxLength: RequiredParams<'field' | 'max'>
		/**
		 * O​ ​c​a​m​p​o​ ​'​{​f​i​e​l​d​}​'​ ​d​e​v​e​ ​t​e​r​ ​e​x​a​t​a​m​e​n​t​e​ ​{​l​e​n​g​t​h​}​ ​c​a​r​a​c​t​e​r​e​s
		 * @param {unknown} field
		 * @param {unknown} length
		 */
		exactLength: RequiredParams<'field' | 'length'>
		/**
		 * O​ ​c​a​m​p​o​ ​'​{​f​i​e​l​d​}​'​ ​d​e​v​e​ ​s​e​r​ ​n​o​ ​m​í​n​i​m​o​ ​{​m​i​n​}
		 * @param {unknown} field
		 * @param {unknown} min
		 */
		minimum: RequiredParams<'field' | 'min'>
		/**
		 * O​ ​c​a​m​p​o​ ​'​{​f​i​e​l​d​}​'​ ​d​e​v​e​ ​s​e​r​ ​n​o​ ​m​á​x​i​m​o​ ​{​m​a​x​}
		 * @param {unknown} field
		 * @param {unknown} max
		 */
		maximum: RequiredParams<'field' | 'max'>
		/**
		 * O​ ​c​a​m​p​o​ ​'​{​f​i​e​l​d​}​'​ ​d​e​v​e​ ​s​e​r​ ​m​a​i​o​r​ ​q​u​e​ ​{​m​i​n​}
		 * @param {unknown} field
		 * @param {unknown} min
		 */
		exclusiveMinimum: RequiredParams<'field' | 'min'>
		/**
		 * O​ ​c​a​m​p​o​ ​'​{​f​i​e​l​d​}​'​ ​d​e​v​e​ ​s​e​r​ ​m​e​n​o​r​ ​q​u​e​ ​{​m​a​x​}
		 * @param {unknown} field
		 * @param {unknown} max
		 */
		exclusiveMaximum: RequiredParams<'field' | 'max'>
		/**
		 * O​ ​c​a​m​p​o​ ​'​{​f​i​e​l​d​}​'​ ​d​e​v​e​ ​s​e​r​ ​t​e​x​t​o
		 * @param {unknown} field
		 */
		expectedString: RequiredParams<'field'>
		/**
		 * O​ ​c​a​m​p​o​ ​'​{​f​i​e​l​d​}​'​ ​d​e​v​e​ ​s​e​r​ ​u​m​ ​n​ú​m​e​r​o
		 * @param {unknown} field
		 */
		expectedNumber: RequiredParams<'field'>
		/**
		 * O​ ​c​a​m​p​o​ ​'​{​f​i​e​l​d​}​'​ ​d​e​v​e​ ​s​e​r​ ​u​m​ ​n​ú​m​e​r​o​ ​i​n​t​e​i​r​o
		 * @param {unknown} field
		 */
		expectedInteger: RequiredParams<'field'>
		/**
		 * O​ ​c​a​m​p​o​ ​'​{​f​i​e​l​d​}​'​ ​d​e​v​e​ ​s​e​r​ ​v​e​r​d​a​d​e​i​r​o​ ​o​u​ ​f​a​l​s​o
		 * @param {unknown} field
		 */
		expectedBoolean: RequiredParams<'field'>
		/**
		 * O​ ​c​a​m​p​o​ ​'​{​f​i​e​l​d​}​'​ ​d​e​v​e​ ​s​e​r​ ​u​m​ ​o​b​j​e​t​o
		 * @param {unknown} field
		 */
		expectedObject: RequiredParams<'field'>
		/**
		 * O​ ​c​a​m​p​o​ ​'​{​f​i​e​l​d​}​'​ ​d​e​v​e​ ​s​e​r​ ​u​m​a​ ​l​i​s​t​a
		 * @param {unknown} field
		 */
		expectedArray: RequiredParams<'field'>
		/**
		 * O​ ​c​a​m​p​o​ ​'​{​f​i​e​l​d​}​'​ ​d​e​v​e​ ​s​e​r​ ​n​u​l​o
		 * @param {unknown} field
		 */
		expectedNull: RequiredParams<'field'>
		/**
		 * O​ ​c​a​m​p​o​ ​'​{​f​i​e​l​d​}​'​ ​é​ ​o​b​r​i​g​a​t​ó​r​i​o
		 * @param {unknown} field
		 */
		required: RequiredParams<'field'>
		/**
		 * P​r​o​p​r​i​e​d​a​d​e​ ​n​ã​o​ ​p​e​r​m​i​t​i​d​a​:​ ​'​{​p​r​o​p​e​r​t​y​}​'
		 * @param {unknown} property
		 */
		additionalProperties: RequiredParams<'property'>
		/**
		 * O​ ​c​a​m​p​o​ ​'​{​f​i​e​l​d​}​'​ ​n​ã​o​ ​c​o​r​r​e​s​p​o​n​d​e​ ​a​o​ ​p​a​d​r​ã​o​ ​e​s​p​e​r​a​d​o
		 * @param {unknown} field
		 */
		pattern: RequiredParams<'field'>
		/**
		 * O​ ​c​a​m​p​o​ ​'​{​f​i​e​l​d​}​'​ ​d​e​v​e​ ​s​e​r​ ​u​m​ ​d​o​s​ ​v​a​l​o​r​e​s​ ​p​e​r​m​i​t​i​d​o​s
		 * @param {unknown} field
		 */
		enumMismatch: RequiredParams<'field'>
		/**
		 * O​ ​c​a​m​p​o​ ​'​{​f​i​e​l​d​}​'​ ​d​e​v​e​ ​t​e​r​ ​n​o​ ​m​í​n​i​m​o​ ​{​m​i​n​}​ ​i​t​e​n​s
		 * @param {unknown} field
		 * @param {unknown} min
		 */
		minItems: RequiredParams<'field' | 'min'>
		/**
		 * O​ ​c​a​m​p​o​ ​'​{​f​i​e​l​d​}​'​ ​d​e​v​e​ ​t​e​r​ ​n​o​ ​m​á​x​i​m​o​ ​{​m​a​x​}​ ​i​t​e​n​s
		 * @param {unknown} field
		 * @param {unknown} max
		 */
		maxItems: RequiredParams<'field' | 'max'>
		/**
		 * O​ ​c​a​m​p​o​ ​'​{​f​i​e​l​d​}​'​ ​n​ã​o​ ​p​o​d​e​ ​t​e​r​ ​i​t​e​n​s​ ​d​u​p​l​i​c​a​d​o​s
		 * @param {unknown} field
		 */
		uniqueItems: RequiredParams<'field'>
		/**
		 * V​a​l​o​r​ ​i​n​v​á​l​i​d​o​ ​p​a​r​a​ ​o​ ​c​a​m​p​o​ ​'​{​f​i​e​l​d​}​'
		 * @param {unknown} field
		 */
		invalidValue: RequiredParams<'field'>
		/**
		 * E​r​r​o​ ​d​e​ ​v​a​l​i​d​a​ç​ã​o​ ​d​e​s​c​o​n​h​e​c​i​d​o
		 */
		unknownError: string
	}
}

export type TranslationFunctions = {
	common: {
		/**
		 * Ocorreu um erro interno
		 */
		internalError: () => LocalizedString
		/**
		 * Erro de validação
		 */
		validationError: () => LocalizedString
		/**
		 * Recurso não encontrado
		 */
		notFound: () => LocalizedString
		/**
		 * Conflito de recurso
		 */
		conflict: () => LocalizedString
		/**
		 * Não autorizado
		 */
		unauthorized: () => LocalizedString
		/**
		 * Acesso negado
		 */
		forbidden: () => LocalizedString
		/**
		 * Operação realizada com sucesso
		 */
		success: () => LocalizedString
		/**
		 * Recurso criado com sucesso
		 */
		created: () => LocalizedString
		/**
		 * Recurso atualizado com sucesso
		 */
		updated: () => LocalizedString
		/**
		 * Recurso excluído com sucesso
		 */
		deleted: () => LocalizedString
		/**
		 * Funcionalidade não implementada
		 */
		notImplemented: () => LocalizedString
	}
	auth: {
		email: {
			/**
			 * Formato de email inválido
			 */
			invalidFormat: () => LocalizedString
			/**
			 * Email muito longo (máximo 254 caracteres)
			 */
			tooLong: () => LocalizedString
		}
		password: {
			/**
			 * Senha obrigatória
			 */
			required: () => LocalizedString
			/**
			 * A senha deve ter pelo menos {minLength} caracteres
			 */
			tooShort: (arg: { minLength: unknown }) => LocalizedString
			/**
			 * A senha deve ter no máximo {maxLength} caracteres
			 */
			tooLong: (arg: { maxLength: unknown }) => LocalizedString
			/**
			 * A senha deve conter pelo menos uma letra maiúscula
			 */
			needsUppercase: () => LocalizedString
			/**
			 * A senha deve conter pelo menos uma letra minúscula
			 */
			needsLowercase: () => LocalizedString
			/**
			 * A senha deve conter pelo menos um número
			 */
			needsNumber: () => LocalizedString
			/**
			 * A senha deve conter pelo menos um caractere especial
			 */
			needsSpecial: () => LocalizedString
			/**
			 * Esta senha é muito comum
			 */
			tooCommon: () => LocalizedString
			/**
			 * Senha inválida
			 */
			invalid: () => LocalizedString
			/**
			 * Falha ao processar senha
			 */
			hashFailed: () => LocalizedString
			/**
			 * Hash de senha não pode estar vazio
			 */
			hashEmpty: () => LocalizedString
			/**
			 * Formato de hash de senha inválido
			 */
			hashInvalid: () => LocalizedString
			/**
			 * Senha deve ter pelo menos 6 caracteres
			 */
			tooShortForHash: () => LocalizedString
		}
		user: {
			/**
			 * Usuário com este email já existe
			 */
			alreadyExists: () => LocalizedString
			/**
			 * Usuário não encontrado
			 */
			notFound: () => LocalizedString
			/**
			 * Falha ao salvar usuário
			 */
			saveFailed: () => LocalizedString
			/**
			 * Usuário registrado com sucesso
			 */
			registeredSuccess: () => LocalizedString
			/**
			 * Login realizado com sucesso
			 */
			loginSuccess: () => LocalizedString
			/**
			 * Logout realizado com sucesso
			 */
			logoutSuccess: () => LocalizedString
			/**
			 * Perfil atualizado com sucesso
			 */
			profileUpdated: () => LocalizedString
			/**
			 * Usuário não possui a role: {role}
			 */
			doesNotHaveRole: (arg: { role: unknown }) => LocalizedString
			/**
			 * Usuário não possui a permissão individual: {permission}
			 */
			doesNotHavePermission: (arg: { permission: unknown }) => LocalizedString
		}
		token: {
			/**
			 * Formato de token inválido
			 */
			invalidFormat: () => LocalizedString
			/**
			 * Token expirado ou inválido
			 */
			expired: () => LocalizedString
			/**
			 * Token renovado com sucesso
			 */
			refreshSuccess: () => LocalizedString
			/**
			 * Token não fornecido
			 */
			missing: () => LocalizedString
			/**
			 * Token malformado
			 */
			malformed: () => LocalizedString
		}
		role: {
			/**
			 * Usuário já possui a role: {role}
			 */
			alreadyHas: (arg: { role: unknown }) => LocalizedString
			/**
			 * Usuário não possui a role: {role}
			 */
			notHas: (arg: { role: unknown }) => LocalizedString
			/**
			 * Não é possível remover a última role do usuário
			 */
			cannotRemoveLast: () => LocalizedString
			/**
			 * Nome da role não pode estar vazio
			 */
			nameRequired: () => LocalizedString
			/**
			 * Nome da role não pode estar vazio
			 */
			nameEmpty: () => LocalizedString
			/**
			 * Nome da role deve ter pelo menos {minLength} caracteres
			 */
			nameTooShort: (arg: { minLength: unknown }) => LocalizedString
			/**
			 * Nome da role deve ter no máximo {maxLength} caracteres
			 */
			nameTooLong: (arg: { maxLength: unknown }) => LocalizedString
			/**
			 * Nome da role deve começar com uma letra e conter apenas letras minúsculas, números e underscores
			 */
			invalidFormat: () => LocalizedString
			/**
			 * Nome da role pode conter apenas letras, números, underscores e hífens
			 */
			invalidChars: () => LocalizedString
			/**
			 * Não é possível criar role com o nome reservado "admin"
			 */
			reservedName: () => LocalizedString
			/**
			 * Apenas "admin" pode ser criado como role de sistema
			 */
			onlyAdminSystem: () => LocalizedString
			/**
			 * Não é possível renomear para o nome reservado "admin"
			 */
			cannotRenameToAdmin: () => LocalizedString
			/**
			 * Role já possui a permissão: {permission}
			 */
			alreadyHasPermission: (arg: { permission: unknown }) => LocalizedString
			/**
			 * Role não possui a permissão: {permission}
			 */
			doesNotHavePermission: (arg: { permission: unknown }) => LocalizedString
			/**
			 * Role '{name}' já existe
			 */
			alreadyExists: (arg: { name: unknown }) => LocalizedString
			/**
			 * Role não encontrada
			 */
			notFound: () => LocalizedString
			/**
			 * Role excluída com sucesso
			 */
			deleted: () => LocalizedString
			/**
			 * Não é possível renomear roles de sistema
			 */
			cannotRenameSystem: () => LocalizedString
			/**
			 * Roles de sistema não podem ser excluídas
			 */
			cannotDeleteSystem: () => LocalizedString
			/**
			 * Role '{role}' atribuída ao usuário com sucesso
			 */
			assigned: (arg: { role: unknown }) => LocalizedString
			/**
			 * Role '{role}' removida do usuário com sucesso
			 */
			removed: (arg: { role: unknown }) => LocalizedString
			/**
			 * Role '{name}' criada com sucesso
			 */
			created: (arg: { name: unknown }) => LocalizedString
			/**
			 * Role '{name}' atualizada com sucesso
			 */
			updated: (arg: { name: unknown }) => LocalizedString
		}
		permission: {
			/**
			 * Já possui a permissão: {permission}
			 */
			alreadyHas: (arg: { permission: unknown }) => LocalizedString
			/**
			 * Não possui a permissão: {permission}
			 */
			notHas: (arg: { permission: unknown }) => LocalizedString
			/**
			 * Permissão '{permission}' não encontrada
			 */
			notFound: (arg: { permission: unknown }) => LocalizedString
			/**
			 * Permissão '{permission}' já existe
			 */
			alreadyExists: (arg: { permission: unknown }) => LocalizedString
			/**
			 * Formato de permissão inválido. Use: recurso:acao
			 */
			invalidFormat: () => LocalizedString
			/**
			 * Permissão '{permission}' atribuída com sucesso
			 */
			assigned: (arg: { permission: unknown }) => LocalizedString
			/**
			 * Permissão '{permission}' removida com sucesso
			 */
			removed: (arg: { permission: unknown }) => LocalizedString
			/**
			 * Permissão '{permission}' atribuída à role com sucesso
			 */
			assignedToRole: (arg: { permission: unknown }) => LocalizedString
			/**
			 * Permissão '{permission}' removida da role com sucesso
			 */
			removedFromRole: (arg: { permission: unknown }) => LocalizedString
			/**
			 * Permissão '{permission}' atribuída ao usuário com sucesso
			 */
			assignedToUser: (arg: { permission: unknown }) => LocalizedString
			/**
			 * Permissão '{permission}' removida do usuário com sucesso
			 */
			removedFromUser: (arg: { permission: unknown }) => LocalizedString
			/**
			 * Role '{role}' já possui a permissão '{permission}'
			 */
			roleAlreadyHas: (arg: { permission: unknown, role: unknown }) => LocalizedString
			/**
			 * Role '{role}' não possui a permissão '{permission}'
			 */
			roleNotHas: (arg: { permission: unknown, role: unknown }) => LocalizedString
			/**
			 * Usuário já possui a permissão individual '{permission}'
			 */
			userAlreadyHas: (arg: { permission: unknown }) => LocalizedString
			/**
			 * Usuário não possui a permissão individual '{permission}'
			 */
			userNotHas: (arg: { permission: unknown }) => LocalizedString
		}
		oauth: {
			/**
			 * Provedor OAuth não suportado: {provider}
			 */
			unsupportedProvider: (arg: { provider: unknown }) => LocalizedString
			/**
			 * OAuth {provider} não está configurado
			 */
			notConfigured: (arg: { provider: unknown }) => LocalizedString
			/**
			 * Facebook não suporta renovação de token
			 */
			facebookNoRefresh: () => LocalizedString
			/**
			 * Email inválido do provedor OAuth: {email}
			 */
			invalidEmail: (arg: { email: unknown }) => LocalizedString
			/**
			 * Conta {provider} vinculada com sucesso
			 */
			linkSuccess: (arg: { provider: unknown }) => LocalizedString
			/**
			 * Conta {provider} desvinculada com sucesso
			 */
			unlinkSuccess: (arg: { provider: unknown }) => LocalizedString
			/**
			 * Você já tem uma conta {provider} vinculada
			 */
			alreadyLinked: (arg: { provider: unknown }) => LocalizedString
			/**
			 * Esta conta {provider} já está vinculada a outro usuário
			 */
			linkedToAnotherUser: (arg: { provider: unknown }) => LocalizedString
			/**
			 * Nenhuma conta {provider} vinculada
			 */
			notLinked: (arg: { provider: unknown }) => LocalizedString
			/**
			 * Não é possível desvincular seu único método de autenticação. Vincule outro provedor ou defina uma senha primeiro.
			 */
			cannotUnlinkOnlyMethod: () => LocalizedString
			/**
			 * Não é possível atualizar perfil com provedor diferente
			 */
			cannotUpdateDifferentProvider: () => LocalizedString
			/**
			 * Não é possível atualizar perfil com ID de provedor diferente
			 */
			cannotUpdateDifferentProviderId: () => LocalizedString
			/**
			 * ID do usuário é obrigatório
			 */
			userIdRequired: () => LocalizedString
			/**
			 * Perfil OAuth é obrigatório
			 */
			profileRequired: () => LocalizedString
			/**
			 * Provedor é obrigatório
			 */
			providerRequired: () => LocalizedString
			/**
			 * OAuthProfile não pode ser criado para autenticação local
			 */
			providerLocalNotAllowed: () => LocalizedString
			/**
			 * ID do usuário no provedor é obrigatório
			 */
			providerUserIdRequired: () => LocalizedString
			/**
			 * Formato de email inválido
			 */
			invalidEmailFormat: () => LocalizedString
			/**
			 * Formato de URL do avatar inválido
			 */
			invalidAvatarUrl: () => LocalizedString
			/**
			 * Falha ao gerar email temporário
			 */
			placeholderEmailFailed: () => LocalizedString
			/**
			 * Falha ao gerar senha segura
			 */
			passwordGenerationFailed: () => LocalizedString
			/**
			 * Provedor OAuth não está configurado
			 */
			providerNotConfigured: () => LocalizedString
			/**
			 * Falha ao gerar URL de autorização
			 */
			authorizationUrlFailed: () => LocalizedString
			/**
			 * Falha ao trocar código por tokens
			 */
			codeExchangeFailed: () => LocalizedString
			/**
			 * Falha ao renovar token
			 */
			tokenRefreshFailed: () => LocalizedString
			/**
			 * Falha ao buscar informações do usuário
			 */
			userInfoFailed: () => LocalizedString
			/**
			 * Provedor OAuth não retornou ID token
			 */
			noIdToken: () => LocalizedString
			/**
			 * Renovação de token da Apple não é suportada por este serviço
			 */
			appleRefreshNotSupported: () => LocalizedString
			/**
			 * Formato de JWT inválido
			 */
			invalidJwtFormat: () => LocalizedString
		}
		provider: {
			/**
			 * Nome do provedor não pode estar vazio
			 */
			empty: () => LocalizedString
			/**
			 * Provedor inválido: {value}. Provedores suportados: {supported}
			 */
			invalid: (arg: { supported: unknown, value: unknown }) => LocalizedString
		}
	}
	permission: {
		/**
		 * Permissão não pode estar vazia
		 */
		empty: () => LocalizedString
		/**
		 * Permissão deve estar no formato recurso:acao (ex: users:read)
		 */
		invalidFormat: () => LocalizedString
		/**
		 * Recurso não pode estar vazio
		 */
		resourceEmpty: () => LocalizedString
		/**
		 * Ação não pode estar vazia
		 */
		actionEmpty: () => LocalizedString
		/**
		 * Recurso deve começar com uma letra e conter apenas letras minúsculas, números e underscores
		 */
		resourceInvalidFormat: () => LocalizedString
		/**
		 * Ação deve começar com uma letra e conter apenas letras minúsculas, números e underscores (ou use * para wildcard)
		 */
		actionInvalidFormat: () => LocalizedString
	}
	refreshToken: {
		/**
		 * Formato de refresh token inválido
		 */
		invalidFormat: () => LocalizedString
	}
	id: {
		/**
		 * Formato de UUID inválido
		 */
		invalidUuid: () => LocalizedString
		/**
		 * ID de usuário inválido
		 */
		invalidUserId: () => LocalizedString
		/**
		 * ID de role inválido
		 */
		invalidRoleId: () => LocalizedString
		/**
		 * ID de permissão inválido
		 */
		invalidPermissionId: () => LocalizedString
		/**
		 * ID de conexão OAuth inválido
		 */
		invalidOAuthConnectionId: () => LocalizedString
		/**
		 * ID é obrigatório
		 */
		required: () => LocalizedString
	}
	http: {
		/**
		 * Bem-vindo ao TypeScript Bun Backend
		 */
		welcome: () => LocalizedString
		/**
		 * Muitas tentativas. Tente novamente mais tarde.
		 */
		rateLimitExceeded: () => LocalizedString
		/**
		 * Muitas tentativas de renovação. Tente novamente mais tarde.
		 */
		rateLimitRefresh: () => LocalizedString
		/**
		 * Muitas tentativas de OAuth. Tente novamente mais tarde.
		 */
		rateLimitOAuth: () => LocalizedString
		/**
		 * Cabeçalho de autorização obrigatório
		 */
		authHeaderRequired: () => LocalizedString
		/**
		 * Formato de autorização inválido. Use: Bearer <token>
		 */
		invalidAuthFormat: () => LocalizedString
		/**
		 * Método não permitido
		 */
		methodNotAllowed: () => LocalizedString
		/**
		 * Rota não encontrada
		 */
		routeNotFound: () => LocalizedString
	}
	middleware: {
		/**
		 * Apenas administradores podem realizar esta ação
		 */
		onlyAdmins: () => LocalizedString
		/**
		 * Usuário criador não encontrado
		 */
		creatorNotFound: () => LocalizedString
		/**
		 * Usuário alvo não encontrado
		 */
		targetNotFound: () => LocalizedString
		/**
		 * Usuário atribuidor não encontrado
		 */
		assignerNotFound: () => LocalizedString
		/**
		 * Usuário removedor não encontrado
		 */
		removerNotFound: () => LocalizedString
		/**
		 * Usuário excluidor não encontrado
		 */
		deleterNotFound: () => LocalizedString
		/**
		 * Permissões insuficientes
		 */
		insufficientPermissions: () => LocalizedString
		/**
		 * Não é possível remover sua própria role de admin
		 */
		cannotRemoveOwnRole: () => LocalizedString
		/**
		 * Não é possível modificar suas próprias permissões
		 */
		cannotModifyOwnPermissions: () => LocalizedString
		/**
		 * Autenticação obrigatória
		 */
		authRequired: () => LocalizedString
		/**
		 * Sessão de usuário inválida
		 */
		invalidSession: () => LocalizedString
		/**
		 * Permissão '{permission}' necessária
		 */
		permissionRequired: (arg: { permission: unknown }) => LocalizedString
		/**
		 * Uma das seguintes permissões é necessária: {permissions}
		 */
		anyPermissionRequired: (arg: { permissions: unknown }) => LocalizedString
		/**
		 * Todas as seguintes permissões são necessárias: {permissions}
		 */
		allPermissionsRequired: (arg: { permissions: unknown }) => LocalizedString
	}
	admin: {
		user: {
			/**
			 * Usuário criado com sucesso
			 */
			created: () => LocalizedString
			/**
			 * Usuário atualizado com sucesso
			 */
			updated: () => LocalizedString
			/**
			 * Usuário desativado com sucesso
			 */
			deactivated: () => LocalizedString
			/**
			 * Usuário reativado com sucesso
			 */
			activated: () => LocalizedString
			/**
			 * Senha redefinida com sucesso
			 */
			passwordReset: () => LocalizedString
			/**
			 * Usuário não encontrado
			 */
			notFound: () => LocalizedString
			/**
			 * Não é possível desativar sua própria conta
			 */
			cannotDeactivateSelf: () => LocalizedString
			/**
			 * Este email já está em uso
			 */
			emailAlreadyExists: () => LocalizedString
			/**
			 * Usuário já está ativo
			 */
			alreadyActive: () => LocalizedString
			/**
			 * Usuário já está inativo
			 */
			alreadyInactive: () => LocalizedString
			/**
			 * Conta de usuário está desativada
			 */
			isInactive: () => LocalizedString
		}
	}
	validation: {
		/**
		 * Campo obrigatório
		 */
		required: () => LocalizedString
		/**
		 * Formato inválido
		 */
		invalidFormat: () => LocalizedString
		/**
		 * Valor muito curto (mínimo {min} caracteres)
		 */
		tooShort: (arg: { min: unknown }) => LocalizedString
		/**
		 * Valor muito longo (máximo {max} caracteres)
		 */
		tooLong: (arg: { max: unknown }) => LocalizedString
		/**
		 * Email inválido
		 */
		invalidEmail: () => LocalizedString
		/**
		 * URL inválida
		 */
		invalidUrl: () => LocalizedString
		/**
		 * Data inválida
		 */
		invalidDate: () => LocalizedString
		/**
		 * Deve ser um número
		 */
		mustBeNumber: () => LocalizedString
		/**
		 * Deve ser um número positivo
		 */
		mustBePositive: () => LocalizedString
		/**
		 * Deve ser um número inteiro
		 */
		mustBeInteger: () => LocalizedString
	}
	mapper: {
		/**
		 * ID de usuário inválido no banco de dados
		 */
		invalidUserId: () => LocalizedString
		/**
		 * Email inválido no banco de dados
		 */
		invalidEmail: () => LocalizedString
		/**
		 * Hash de senha inválido no banco de dados
		 */
		invalidPasswordHash: () => LocalizedString
		/**
		 * ID de conexão OAuth inválido no banco de dados
		 */
		invalidOAuthConnectionId: () => LocalizedString
		/**
		 * Provedor inválido no banco de dados
		 */
		invalidProvider: () => LocalizedString
	}
	dateTime: {
		/**
		 * Hoje
		 */
		today: () => LocalizedString
		/**
		 * Ontem
		 */
		yesterday: () => LocalizedString
		/**
		 * Amanhã
		 */
		tomorrow: () => LocalizedString
		/**
		 * há {count} dias
		 */
		daysAgo: (arg: { count: unknown }) => LocalizedString
		/**
		 * há {count} horas
		 */
		hoursAgo: (arg: { count: unknown }) => LocalizedString
		/**
		 * há {count} minutos
		 */
		minutesAgo: (arg: { count: unknown }) => LocalizedString
		/**
		 * agora mesmo
		 */
		justNow: () => LocalizedString
	}
	validationErrors: {
		/**
		 * O campo '{field}' deve ser um email válido
		 */
		emailFormat: (arg: { field: unknown }) => LocalizedString
		/**
		 * O campo '{field}' deve ser uma URL válida
		 */
		urlFormat: (arg: { field: unknown }) => LocalizedString
		/**
		 * O campo '{field}' deve ser um UUID válido
		 */
		uuidFormat: (arg: { field: unknown }) => LocalizedString
		/**
		 * O campo '{field}' deve ser uma data válida
		 */
		dateFormat: (arg: { field: unknown }) => LocalizedString
		/**
		 * O campo '{field}' deve ser uma data/hora válida
		 */
		dateTimeFormat: (arg: { field: unknown }) => LocalizedString
		/**
		 * O campo '{field}' deve ser um horário válido
		 */
		timeFormat: (arg: { field: unknown }) => LocalizedString
		/**
		 * O campo '{field}' deve ter no mínimo {min} caracteres
		 */
		minLength: (arg: { field: unknown, min: unknown }) => LocalizedString
		/**
		 * O campo '{field}' deve ter no máximo {max} caracteres
		 */
		maxLength: (arg: { field: unknown, max: unknown }) => LocalizedString
		/**
		 * O campo '{field}' deve ter exatamente {length} caracteres
		 */
		exactLength: (arg: { field: unknown, length: unknown }) => LocalizedString
		/**
		 * O campo '{field}' deve ser no mínimo {min}
		 */
		minimum: (arg: { field: unknown, min: unknown }) => LocalizedString
		/**
		 * O campo '{field}' deve ser no máximo {max}
		 */
		maximum: (arg: { field: unknown, max: unknown }) => LocalizedString
		/**
		 * O campo '{field}' deve ser maior que {min}
		 */
		exclusiveMinimum: (arg: { field: unknown, min: unknown }) => LocalizedString
		/**
		 * O campo '{field}' deve ser menor que {max}
		 */
		exclusiveMaximum: (arg: { field: unknown, max: unknown }) => LocalizedString
		/**
		 * O campo '{field}' deve ser texto
		 */
		expectedString: (arg: { field: unknown }) => LocalizedString
		/**
		 * O campo '{field}' deve ser um número
		 */
		expectedNumber: (arg: { field: unknown }) => LocalizedString
		/**
		 * O campo '{field}' deve ser um número inteiro
		 */
		expectedInteger: (arg: { field: unknown }) => LocalizedString
		/**
		 * O campo '{field}' deve ser verdadeiro ou falso
		 */
		expectedBoolean: (arg: { field: unknown }) => LocalizedString
		/**
		 * O campo '{field}' deve ser um objeto
		 */
		expectedObject: (arg: { field: unknown }) => LocalizedString
		/**
		 * O campo '{field}' deve ser uma lista
		 */
		expectedArray: (arg: { field: unknown }) => LocalizedString
		/**
		 * O campo '{field}' deve ser nulo
		 */
		expectedNull: (arg: { field: unknown }) => LocalizedString
		/**
		 * O campo '{field}' é obrigatório
		 */
		required: (arg: { field: unknown }) => LocalizedString
		/**
		 * Propriedade não permitida: '{property}'
		 */
		additionalProperties: (arg: { property: unknown }) => LocalizedString
		/**
		 * O campo '{field}' não corresponde ao padrão esperado
		 */
		pattern: (arg: { field: unknown }) => LocalizedString
		/**
		 * O campo '{field}' deve ser um dos valores permitidos
		 */
		enumMismatch: (arg: { field: unknown }) => LocalizedString
		/**
		 * O campo '{field}' deve ter no mínimo {min} itens
		 */
		minItems: (arg: { field: unknown, min: unknown }) => LocalizedString
		/**
		 * O campo '{field}' deve ter no máximo {max} itens
		 */
		maxItems: (arg: { field: unknown, max: unknown }) => LocalizedString
		/**
		 * O campo '{field}' não pode ter itens duplicados
		 */
		uniqueItems: (arg: { field: unknown }) => LocalizedString
		/**
		 * Valor inválido para o campo '{field}'
		 */
		invalidValue: (arg: { field: unknown }) => LocalizedString
		/**
		 * Erro de validação desconhecido
		 */
		unknownError: () => LocalizedString
	}
}

export type Formatters = {}
